CURRENCY_DATA = {
		"Alchemy Shard" : "alchemyShard",
		"Alteration Shard" : "alterationShard",
		"Scroll Fragment" : "scrollFragment",
		"Armourer's Scrap" : "armourScrap",
		"Blacksmith's Whetstone" : "blacksmithWhetstone",
		"Blessed Orb" : "blessedOrb",
		"Chaos Orb" : "chaosOrb",
		"Chromatic Orb" : "chromaticOrb",
		"Divine Orb" : "divineOrb",
		"Exalted Orb" : "exaltedOrb",
		"Gemcutter's Prism" : "GCP",
		"Glassblower's Bauble" : "bauble",
		"Jeweler's Orb" : "jewelersOrb",
		"Mirror of Kalandra" : "mirrorOfKalandra",
		"Orb of Alchemy" : "alchemyOrb",
		"Orb of Alteration" : "alterationOrb",
		"Orb of Augmentation": "augmentationOrb",
		"Orb of Chance" : "chanceOrb",
		"Orb of Fusing" : "fusingOrb",
		"Orb of Regret" : "regretOrb",
		"Orb of Scouring" : "scouringOrb",
		"Orb of Transmutation" : "transmutationOrb",
		"Portal Scroll" : "portalScroll",
		"Regal Orb" : "regalOrb",
		"Scroll of Wisdom" : "wisdomScroll",
		"Transmutation Shard" : "transmutationShard",
		"Combined Amulet": 'questItem',
		"Baelful Gem": 'questItem',
		"Wicked Spear": 'questItem',
		"Cartographer's Chisel": 'cartographerChisel'
}