ITEM_TYPE_DATA = {
	"Crude Bow": "weapon2h",
	"Short Bow": "weapon2h",
	"Long Bow": "weapon2h",
	"Composite Bow": "weapon2h",
	"Recurve Bow": "weapon2h",
	"Bone Bow": "weapon2h",
	"Royal Bow": "weapon2h",
	"Death Bow": "weapon2h",
	"Grove Bow": "weapon2h",
	"Decurve Bow": "weapon2h",
	"Compound Bow": "weapon2h",
	"Sniper Bow": "weapon2h",
	"Ivory Bow": "weapon2h",
	"Highborn Bow": "weapon2h",
	"Decimation Bow": "weapon2h",
	"Thicket Bow": "weapon2h",
	"Citadel Bow": "weapon2h",
	"Ranger Bow": "weapon2h",
	"Maraketh Bow": "weapon2h",
	"Chimeric Bow": "weapon2h",
	"Imperial Bow": "weapon2h",
	"Armageddon Bow": "weapon2h",
	"Nailed Fist": "weapon1h",
	"Sharktooth Claw": "weapon1h",
	"Awl": "weapon1h",
	"Cat's Paw": "weapon1h",
	"Blinder": "weapon1h",
	"Timeworn Claw": "weapon1h",
	"Sparkling Claw": "weapon1h",
	"Fright Claw": "weapon1h",
	"Thresher Claw": "weapon1h",
	"Gouger": "weapon1h",
	"Tiger's Paw": "weapon1h",
	"Gut Ripper": "weapon1h",
	"Prehistoric Claw": "weapon1h",
	"Noble Claw": "weapon1h",
	"Dread Claw": "weapon1h",
	"Great White Claw": "weapon1h",
	"Throat Stabber": "weapon1h",
	"Hellion's Paw": "weapon1h",
	"Eye Gouger": "weapon1h",
	"Vaal Claw": "weapon1h",
	"Imperial Claw": "weapon1h",
	"Terror Claw": "weapon1h",
	"Glass Shank": "weapon1h",
	"Skinning Knife": "weapon1h",
	"Carving Knife": "weapon1h",
	"Stiletto": "weapon1h",
	"Boot Knife": "weapon1h",
	"Copper Kris": "weapon1h",
	"Skean": "weapon1h",
	"Imp Dagger": "weapon1h",
	"Flaying Knife": "weapon1h",
	"Butcher Knife": "weapon1h",
	"Poignard": "weapon1h",
	"Boot Blade": "weapon1h",
	"Golden Kris": "weapon1h",
	"Royal Skean": "weapon1h",
	"Fiend Dagger": "weapon1h",
	"Gutting Knife": "weapon1h",
	"Slaughter Knife": "weapon1h",
	"Ambusher": "weapon1h",
	"Ezomyte Dagger": "weapon1h",
	"Platinum Kris": "weapon1h",
	"Imperial Skean": "weapon1h",
	"Demon Dagger": "weapon1h",
	"Rusted Hatchet": "weapon1h",
	"Jade Hatchet": "weapon1h",
	"Boarding Axe": "weapon1h",
	"Cleaver": "weapon1h",
	"Broad Axe": "weapon1h",
	"Arming Axe": "weapon1h",
	"Decorative Axe": "weapon1h",
	"Spectral Axe": "weapon1h",
	"Jasper Axe": "weapon1h",
	"Tomahawk": "weapon1h",
	"Wrist Chopper": "weapon1h",
	"War Axe": "weapon1h",
	"Chest Splitter": "weapon1h",
	"Ceremonial Axe": "weapon1h",
	"Wraith Axe": "weapon1h",
	"Karui Axe": "weapon1h",
	"Siege Axe": "weapon1h",
	"Reaver Axe": "weapon1h",
	"Ezomyte Axe": "weapon1h",
	"Vaal Hatchet": "weapon1h",
	"Royal Axe": "weapon1h",
	"Infernal Axe": "weapon1h",
	"Driftwood Club": "weapon1h",
	"Tribal Club": "weapon1h",
	"Spiked Club": "weapon1h",
	"Stone Hammer": "weapon1h",
	"War Hammer": "weapon1h",
	"Bladed Mace": "weapon1h",
	"Ceremonial Mace": "weapon1h",
	"Dream Mace": "weapon1h",
	"Petrified Club": "weapon1h",
	"Barbed Club": "weapon1h",
	"Rock Breaker": "weapon1h",
	"Battle Hammer": "weapon1h",
	"Flanged Mace": "weapon1h",
	"Ornate Mace": "weapon1h",
	"Phantom Mace": "weapon1h",
	"Ancestral Club": "weapon1h",
	"Tenderizer": "weapon1h",
	"Gavel": "weapon1h",
	"Legion Hammer": "weapon1h",
	"Pernarch": "weapon1h",
	"Auric Mace": "weapon1h",
	"Nightmare Mace": "weapon1h",
	"Rusted Sword": "weapon1h",
	"Copper Sword": "weapon1h",
	"Sabre": "weapon1h",
	"Broad Sword": "weapon1h",
	"War Sword": "weapon1h",
	"Ancient Sword": "weapon1h",
	"Elegant Sword": "weapon1h",
	"Dusk Blade": "weapon1h",
	"Variscite Blade": "weapon1h",
	"Cutlass": "weapon1h",
	"Baselard": "weapon1h",
	"Battle Sword": "weapon1h",
	"Elder Sword": "weapon1h",
	"Graceful Sword": "weapon1h",
	"Twilight Blade": "weapon1h",
	"Gemstone Sword": "weapon1h",
	"Corsair Sword": "weapon1h",
	"Gladius": "weapon1h",
	"Legion Sword": "weapon1h",
	"Vaal Blade": "weapon1h",
	"Eternal Sword": "weapon1h",
	"Midnight Blade": "weapon1h",
	"Driftwood Sceptre": "weapon1h",
	"Darkwood Sceptre": "weapon1h",
	"Bronze Sceptre": "weapon1h",
	"Quartz Sceptre": "weapon1h",
	"Iron Sceptre": "weapon1h",
	"Ochre Sceptre": "weapon1h",
	"Ritual Sceptre": "weapon1h",
	"Shadow Sceptre": "weapon1h",
	"Grinning Fetish": "weapon1h",
	"Sekhem": "weapon1h",
	"Crystal Sceptre": "weapon1h",
	"Lead Sceptre": "weapon1h",
	"Blood Sceptre": "weapon1h",
	"Royal Sceptre": "weapon1h",
	"Abyssal Sceptre": "weapon1h",
	"Karui Sceptre": "weapon1h",
	"Tyrant's Sekhem": "weapon1h",
	"Opal Sceptre": "weapon1h",
	"Platinum Sceptre": "weapon1h",
	"Carnal Sceptre": "weapon1h",
	"Vaal Sceptre": "weapon1h",
	"Void Sceptre": "weapon1h",
	"Gnarled Branch": "weapon2h",
	"Primitive Staff": "weapon2h",
	"Long Staff": "weapon2h",
	"Iron Staff": "weapon2h",
	"Coiled Staff": "weapon2h",
	"Royal Staff": "weapon2h",
	"Vile Staff": "weapon2h",
	"Woodful Staff": "weapon2h",
	"Quarterstaff": "weapon2h",
	"Military Staff": "weapon2h",
	"Serpentine Staff": "weapon2h",
	"Highborn Staff": "weapon2h",
	"Foul Staff": "weapon2h",
	"Primordial Staff": "weapon2h",
	"Lathi": "weapon2h",
	"Ezoymte Staff": "weapon2h",
	"Maelström Staff": "weapon2h",
	"Imperial Staff": "weapon2h",
	"Damnation Staff": "weapon2h",
	"Rusted Spike": "weapon1h",
	"Whalebone Rapier": "weapon1h",
	"Battered Foil": "weapon1h",
	"Basket Rapier": "weapon1h",
	"Jagged Foil": "weapon1h",
	"Antique Rapier": "weapon1h",
	"Elegant Foil": "weapon1h",
	"Thorn Rapier": "weapon1h",
	"Wyrmbone Rapier": "weapon1h",
	"Burnished Foil": "weapon1h",
	"Estoc": "weapon1h",
	"Serrated Foil": "weapon1h",
	"Primeval Rapier": "weapon1h",
	"Fancy Foil": "weapon1h",
	"Apex Rapier": "weapon1h",
	"Dragonbone Rapier": "weapon1h",
	"Tempered Foil": "weapon1h",
	"Pecoraro": "weapon1h",
	"Spiraled Foil": "weapon1h",
	"Vaal Rapier": "weapon1h",
	"Jeweled Foil": "weapon1h",
	"Harpy Rapier": "weapon1h",
	"Stone Axe": "weapon2h",
	"Jade Chopper": "weapon2h",
	"Woodsplitter": "weapon2h",
	"Poleaxe": "weapon2h",
	"Double Axe": "weapon2h",
	"Gilded Axe": "weapon2h",
	"Shadow Axe": "weapon2h",
	"Jasper Chopper": "weapon2h",
	"Timber Axe": "weapon2h",
	"Headsman Axe": "weapon2h",
	"Labrys": "weapon2h",
	"Noble Axe": "weapon2h",
	"Abyssal Axe": "weapon2h",
	"Karui Chopper": "weapon2h",
	"Sundering Axe": "weapon2h",
	"Ezomyte Axe": "weapon2h",
	"Vaal Axe": "weapon2h",
	"Despot Axe": "weapon2h",
	"Void Axe": "weapon2h",
	"Driftwood Maul": "weapon2h",
	"Tribal Maul": "weapon2h",
	"Mallet": "weapon2h",
	"Sledgehammer": "weapon2h",
	"Spiked Maul": "weapon2h",
	"Brass Maul": "weapon2h",
	"Fright Maul": "weapon2h",
	"Totemic Maul": "weapon2h",
	"Great Mallet": "weapon2h",
	"Steelhead": "weapon2h",
	"Spiny Maul": "weapon2h",
	"Plated Maul": "weapon2h",
	"Dread Maul": "weapon2h",
	"Karui Maul": "weapon2h",
	"Colossus Mallet": "weapon2h",
	"Piledriver": "weapon2h",
	"Meatgrinder": "weapon2h",
	"Imperial Maul": "weapon2h",
	"Terror Maul": "weapon2h",
	"Corroded Blade": "weapon2h",
	"Long Sword": "weapon2h",
	"Bastard Sword": "weapon2h",
	"Two-Handed Sword": "weapon2h",
	"Etched Greatsword": "weapon2h",
	"Ornate Sword": "weapon2h",
	"Spectral Sword": "weapon2h",
	"Butcher Sword": "weapon2h",
	"Footman Sword": "weapon2h",
	"Highland Blade": "weapon2h",
	"Engraved Greatsword": "weapon2h",
	"Tiger Sword": "weapon2h",
	"Wraith Sword": "weapon2h",
	"Headman's Sword": "weapon2h",
	"Reaver Sword": "weapon2h",
	"Ezomyte Blade": "weapon2h",
	"Vaal Greatsword": "weapon2h",
	"Lion Sword": "weapon2h",
	"Infernal Sword": "weapon2h",
	"Driftwood Wand": "weapon1h",
	"Goat's Horn": "weapon1h",
	"Carved Wand": "weapon1h",
	"Quartz Wand": "weapon1h",
	"Spiraled Wand": "weapon1h",
	"Sage Wand": "weapon1h",
	"Faun's Horn": "weapon1h",
	"Engraved Wand": "weapon1h",
	"Crystal Wand": "weapon1h",
	"Serpent Wand": "weapon1h",
	"Omen Wand": "weapon1h",
	"Demon's Horn": "weapon1h",
	"Imbued Wand": "weapon1h",
	"Opal Wand": "weapon1h",
	"Tornado Wand": "weapon1h",
	"Prophecy Wand": "weapon1h",
	"Plate Vest": "chest",
	"Shabby Jerkin": "chest",
	"Simple Robe": "chest",
	"Chainmail Vest": "chest",
	"Scale Vest": "chest",
	"Padded Vest": "chest",
	"Chestplate": "chest",
	"Light Brigandine": "chest",
	"Chainmail Tunic": "chest",
	"Strapped Leather": "chest",
	"Oiled Vest": "chest",
	"Silken Vest": "chest",
	"Ringmail Coat": "chest",
	"Copper Plate": "chest",
	"Buckskin Tunic": "chest",
	"Scale Doublet": "chest",
	"Padded Jacket": "chest",
	"Scholar's Robe": "chest",
	"War Plate": "chest",
	"Chainmail Doublet": "chest",
	"Infantry Brigandine": "chest",
	"Oiled Coat": "chest",
	"Silken Garb": "chest",
	"Wild Leather": "chest",
	"Mage's Vestment": "chest",
	"Full Scale Armor": "chest",
	"Full Leather": "chest",
	"Full Ringmail": "chest",
	"Scarlet Raiment": "chest",
	"Full Plate": "chest",
	"Sun Leather": "chest",
	"Waxed Garb": "chest",
	"Soldier's Brigandine": "chest",
	"Arena Plate": "chest",
	"Full Chainmail": "chest",
	"Silk Robe": "chest",
	"Field Lamellar": "chest",
	"Cabalist Regalia": "chest",
	"Holy Chainmail": "chest",
	"Bone Armor": "chest",
	"Thief's Garb": "chest",
	"Lordly Plate": "chest",
	"Bronze Plate": "chest",
	"Eelskin Tunic": "chest",
	"Sage's Robe": "chest",
	"Wyrmscale Doublet": "chest",
	"Latticed Ringmail": "chest",
	"Quilted Jacket": "chest",
	"Silken Wrap": "chest",
	"Frontier Leather": "chest",
	"Battle Plate": "chest",
	"Hussar Brigandine": "chest",
	"Crusader Chainmail": "chest",
	"Sleek Coat": "chest",
	"Sun Plate": "chest",
	"Glorious Leather": "chest",
	"Conjurer's Vestment": "chest",
	"Full Wyrmscale": "chest",
	"Ornate Ringmail": "chest",
	"Crimson Raiment": "chest",
	"Coronal Leather": "chest",
	"Colosseum Plate": "chest",
	"Spidersilk Robe": "chest",
	"Commander's Brigandine": "chest",
	"Chain Hauberk": "chest",
	"Lacquered Garb": "chest",
	"Majestic Plate": "chest",
	"Cutthroat's Garb": "chest",
	"Destroyer Regalia": "chest",
	"Battle Lamellar": "chest",
	"Devout Chainmail": "chest",
	"Golden Plate": "chest",
	"Crypt Armor": "chest",
	"Savant's Robe": "chest",
	"Sharkskin Tunic": "chest",
	"Dragonscale Doublet": "chest",
	"Loricated Ringmail": "chest",
	"Sentinel Jacket": "chest",
	"Destiny Leather": "chest",
	"Necromancer Silks": "chest",
	"Crusader Plate": "chest",
	"Cavalry Brigandine": "chest",
	"Conquest Chainmail": "chest",
	"Varnished Coat": "chest",
	"Astral Plate": "chest",
	"Occultist's Vestment": "chest",
	"Exquisite Leather": "chest",
	"Full Dragonscale": "chest",
	"Elegant Ringmail": "chest",
	"Zodiac Leather": "chest",
	"Blood Raiment": "chest",
	"Widowsilk Robe": "chest",
	"Gladiator Plate": "chest",
	"General's Brigandine": "chest",
	"Saint's Hauberk": "chest",
	"Vaal Regalia": "chest",
	"Sadist Garb": "chest",
	"Glorious Plate": "chest",
	"Assassin's Garb": "chest",
	"Triumphant Lamellar": "chest",
	"Saintly Chainmail": "chest",
	"Carnal Armor": "chest",
	"Iron Greaves": "feet",
	"Rawhide Boots": "feet",
	"Wool Shoes": "feet",
	"Chain Boots": "feet",
	"Leatherscale Boots": "feet",
	"Wrapped Boots": "feet",
	"Velvet Slippers": "feet",
	"Steel Greaves": "feet",
	"Goathide Boots": "feet",
	"Ringmail Boots": "feet",
	"Strapped Boots": "feet",
	"Ironscale Boots": "feet",
	"Silk Slippers": "feet",
	"Deerskin Boots": "feet",
	"Plated Greaves": "feet",
	"Clasped Boots": "feet",
	"Mesh Boots": "feet",
	"Bronzescale Boots": "feet",
	"Scholar Boots": "feet",
	"Reinforced Greaves": "feet",
	"Shackled Boots": "feet",
	"Nubuck Boots": "feet",
	"Riveted Boots": "feet",
	"Steelscale Boots": "feet",
	"Antique Greaves": "feet",
	"Satin Slippers": "feet",
	"Eelskin Boots": "feet",
	"Zealot Boots": "feet",
	"Trapper Boots": "feet",
	"Serpentscale Boots": "feet",
	"Samite Slippers": "feet",
	"Sharkskin Boots": "feet",
	"Ancient Greaves": "feet",
	"Ambush Boots": "feet",
	"Horseman's Boots": "feet",
	"Wyrmscale Boots": "feet",
	"Conjuror Boots": "feet",
	"Goliath Greaves": "feet",
	"Shagreen Boots": "feet",
	"Carnal Boots": "feet",
	"Cavalry Boots": "feet",
	"Hydrascale Boots": "feet",
	"Arcanist Slippers": "feet",
	"Vaal Greaves": "feet",
	"Stealth Boots": "feet",
	"Assassin's Boots": "feet",
	"Crusader Boots": "feet",
	"Dragonscale Boots": "feet",
	"Sorcerer Boots": "feet",
	"Titan Greaves": "feet",
	"Murder Boots": "feet",
	"Slink Boots": "feet",
	"Iron Gauntlets": "hands",
	"Rawhide Gloves": "hands",
	"Wool Gloves": "hands",
	"Fishscale Gauntlets": "hands",
	"Wrapped Mitts": "hands",
	"Chain Gloves": "hands",
	"Goathide Gloves": "hands",
	"Plated Gauntlets": "hands",
	"Velvet Gloves": "hands",
	"Ironscale Gauntlets": "hands",
	"Strapped Mitts": "hands",
	"Ringmail Gloves": "hands",
	"Deerskin Gloves": "hands",
	"Bronze Gauntlets": "hands",
	"Silk Gloves": "hands",
	"Bronzescale Gauntlets": "hands",
	"Clasped Mitts": "hands",
	"Mesh Gloves": "hands",
	"Nubuck Gloves": "hands",
	"Steel Gauntlets": "hands",
	"Trapper Mitts": "hands",
	"Embroidered Gloves": "hands",
	"Steelscale Gauntlets": "hands",
	"Riveted Gloves": "hands",
	"Eelskin Gloves": "hands",
	"Antique Gauntlets": "hands",
	"Satin Gloves": "hands",
	"Serpentscale Gauntlets": "hands",
	"Zealot Gloves": "hands",
	"Sharkskin Gloves": "hands",
	"Ambush Mitts": "hands",
	"Ancient Gauntlets": "hands",
	"Samite Gloves": "hands",
	"Wyrmscale Gauntlets": "hands",
	"Carnal Mitts": "hands",
	"Horseman's Gloves": "hands",
	"Goliath Gauntlets": "hands",
	"Shagreen Gloves": "hands",
	"Conjuror Gloves": "hands",
	"Cavalry Gloves": "hands",
	"Assassin's Mitts": "hands",
	"Hydrascale Gauntlets": "hands",
	"Arcanist Gloves": "hands",
	"Stealth Gloves": "hands",
	"Vaal Gauntlets": "hands",
	"Crusader Gloves": "hands",
	"Murder Mitts": "hands",
	"Dragonscale Gauntlets": "hands",
	"Titan Gauntlets": "hands",
	"Sorcerer Gloves": "hands",
	"Slink Gloves": "hands",
	"Rusted Casque": "head",
	"Battered Cap": "head",
	"Vine Circlet": "head",
	"Tarnished Mask": "head",
	"Rusted Helmet": "head",
	"Corroded Chain Coif": "head",
	"Footman's Casque": "head",
	"Copper Circlet": "head",
	"Wooden Mask": "head",
	"Leather Cap": "head",
	"Chainmail Coif": "head",
	"Flanged Helmet": "head",
	"Copper Mask": "head",
	"Tribal Circlet": "head",
	"Gladiator Casque": "head",
	"Leather Hood": "head",
	"Ringmail Coif": "head",
	"Ribbed Helmet": "head",
	"Gemmed Circlet": "head",
	"Executioner Casque": "head",
	"Ceremonial Mask": "head",
	"Studded Hood": "head",
	"Inlaid Chain Coif": "head",
	"Gilded Helmet": "head",
	"Gilded Circlet": "head",
	"Imperial Casque": "head",
	"Bandit Mask": "head",
	"Coolus Helmet": "head",
	"Woven Ring Coif": "head",
	"Iron Mask": "head",
	"Carved Circlet": "head",
	"Reaver Casque": "head",
	"Hunter Cap": "head",
	"Finned Helmet": "head",
	"Mesh Chain Coif": "head",
	"Heathen Mask": "head",
	"Forest Hood": "head",
	"Encrusted Circlet": "head",
	"Mercenary Casque": "head",
	"Ornate Helmet": "head",
	"Assassin Mask": "head",
	"Zealot's Chain Coif": "head",
	"Gleaming Circlet": "head",
	"Vaal Casque": "head",
	"Grove Hood": "head",
	"Steel Mask": "head",
	"Commander's Ring Coif": "head",
	"Polished Helmet": "head",
	"Petrified Circlet": "head",
	"Destroyer Casque": "head",
	"Huntress Cap": "head",
	"Pagan Mask": "head",
	"Bladed Helmet": "head",
	"Crusader's Chain Coif": "head",
	"Thicket Hood": "head",
	"Royal Circlet": "head",
	"Annihilator Casque": "head",
	"Crested Helmet": "head",
	"Murder Mask": "head",
	"Imperial Chain Coif": "head",
	"Armageddon Casque": "head",
	"Ezomyte Circlet": "head",
	"Jungle Hood": "head",
	"Splintered Tower Shield": "shield",
	"Goathide Buckler": "shield",
	"Twig Spirit Shield": "shield",
	"Corroded Tower Shield": "shield",
	"Rotted Round Shield": "shield",
	"Spiked Bundle": "shield",
	"Plank Kite Shield": "shield",
	"Pine Buckler": "shield",
	"Yew Spirit Shield": "shield",
	"Rawhide Tower Shield": "shield",
	"Driftwood Spiked Shield": "shield",
	"Fir Round Shield": "shield",
	"Linden Kite Shield": "shield",
	"Bone Spirit Shield": "shield",
	"Painted Buckler": "shield",
	"Cedar Tower Shield": "shield",
	"Alloyed Spike Shield": "shield",
	"Studded Round Shield": "shield",
	"Reinforced Kite Shield": "shield",
	"Hammered Buckler": "shield",
	"Tarnished Spirit Shield": "shield",
	"Copper Tower Shield": "shield",
	"Layered Kite Shield": "shield",
	"Burnished Spike Shield": "shield",
	"Scarlet Round Shield": "shield",
	"Jingling Spirit Shield": "shield",
	"War Buckler": "shield",
	"Reinforced Tower Shield": "shield",
	"Brass Spirit Shield": "shield",
	"Ornate Spiked Shield": "shield",
	"Splendid Round Shield": "shield",
	"Ceremonial Kite Shield": "shield",
	"Gilded Buckler": "shield",
	"Painted Tower Shield": "shield",
	"Walnut Spirit Shield": "shield",
	"Oak Buckler": "shield",
	"Maple Round Shield": "shield",
	"Buckskin Tower Shield": "shield",
	"Redwood Spiked Shield": "shield",
	"Etched Shield": "shield",
	"Ivory Spirit Shield": "shield",
	"Enameled Buckler": "shield",
	"Mahogany Tower Shield": "shield",
	"Compound Spiked Shield": "shield",
	"Spiked Round Shield": "shield",
	"Ancient Spirit Shield": "shield",
	"Steel Kite Shield": "shield",
	"Corrugated Buckler": "shield",
	"Bronze Tower Shield": "shield",
	"Chiming Spirit Shield": "shield",
	"Polished Spiked Shield": "shield",
	"Crimson Round Shield": "shield",
	"Laminated Kite Shield": "shield",
	"Battle Buckler": "shield",
	"Girded Tower Shield": "shield",
	"Thorium Spirit Shield": "shield",
	"Baroque Round Shield": "shield",
	"Sovereign Spiked Shield": "shield",
	"Golden Buckler": "shield",
	"Crested Tower Shield": "shield",
	"Angel Kite Shield": "shield",
	"Lacewood Spirit Shield": "shield",
	"Ironwood Buckler": "shield",
	"Teak Round Shield": "shield",
	"Shagreen Tower Shield": "shield",
	"Alder Spike Shield": "shield",
	"Fossilized Spirit Shield": "shield",
	"Branded Kite Shield": "shield",
	"Lacquered Buckler": "shield",
	"Hunting Shield": "shield",
	"Ebony Tower Shield": "shield",
	"Ezomyte Spiked Shield": "shield",
	"Vaal Spirit Shield": "shield",
	"Spiny Round Shield": "shield",
	"Champion Kite Shield": "shield",
	"Vaal Buckler": "shield",
	"Ezomyte Tower Shield": "shield",
	"Mosaic Kite Shield": "shield",
	"Harmonic Spirit Shield": "shield",
	"Crusader Buckler": "shield",
	"Mirrored Spiked Shield": "shield",
	"Cardinal Round Shield": "shield",
	"Colossal Tower Shield": "shield",
	"Archon Kite Shield": "shield",
	"Titanium Spirit Shield": "shield",
	"Imperial Buckler": "shield",
	"Elegant Round Shield": "shield",
	"Pinnacle Tower Shield": "shield",
	"Supreme Spiked Shield": "shield"
};
