MOD_PREFIX_DATA = {
	"Lacquered": {"type": "Armour","level": 1,"stats": {"Base Physical Damage Reduction Rating": {"min": 3,"max": 10}}},
	"Studded": {"type": "Armour","level": 18,"stats": {"Base Physical Damage Reduction Rating": {"min": 11,"max": 35}}},
	"Ribbed": {"type": "Armour","level": 30,"stats": {"Base Physical Damage Reduction Rating": {"min": 36,"max": 60}}},
	"Fortified": {"type": "Armour","level": 44,"stats": {"Base Physical Damage Reduction Rating": {"min": 61,"max": 80}}},
	"Plated": {"type": "Armour","level": 57,"stats": {"Base Physical Damage Reduction Rating": {"min": 81,"max": 120}}},
	"Lacquered": {"type": "Armour","level": 1,"stats": {"Local Base Physical Damage Reduction Rating": {"min": 3,"max": 10}}},
	"Studded": {"type": "Armour","level": 18,"stats": {"Local Base Physical Damage Reduction Rating": {"min": 11,"max": 35}}},
	"Ribbed": {"type": "Armour","level": 30,"stats": {"Local Base Physical Damage Reduction Rating": {"min": 36,"max": 60}}},
	"Fortified": {"type": "Armour","level": 46,"stats": {"Local Base Physical Damage Reduction Rating": {"min": 61,"max": 80}}},
	"Plated": {"type": "Armour","level": 59,"stats": {"Local Base Physical Damage Reduction Rating": {"min": 81,"max": 120}}},
	"Reinforced": {"type": "Armour","level": 3,"stats": {"Local Physical Damage Reduction Rating +%": {"min": 11,"max": 28}}},
	"Layered": {"type": "Armour","level": 17,"stats": {"Local Physical Damage Reduction Rating +%": {"min": 29,"max": 46}}},
	"Lobstered": {"type": "Armour","level": 29,"stats": {"Local Physical Damage Reduction Rating +%": {"min": 47,"max": 64}}},
	"Buttressed": {"type": "Armour","level": 42,"stats": {"Local Physical Damage Reduction Rating +%": {"min": 65,"max": 82}}},
	"Thickened": {"type": "Armour","level": 60,"stats": {"Local Physical Damage Reduction Rating +%": {"min": 83,"max": 100}}},
	"Reinforced": {"type": "Armour","level": 2,"stats": {"Physical Damage Reduction Rating +%": {"min": 2,"max": 4}}},
	"Layered": {"type": "Armour","level": 18,"stats": {"Physical Damage Reduction Rating +%": {"min": 5,"max": 7}}},
	"Lobstered": {"type": "Armour","level": 30,"stats": {"Physical Damage Reduction Rating +%": {"min": 8,"max": 10}}},
	"Buttressed": {"type": "Armour","level": 42,"stats": {"Physical Damage Reduction Rating +%": {"min": 11,"max": 13}}},
	"Thickened": {"type": "Armour","level": 56,"stats": {"Physical Damage Reduction Rating +%": {"min": 14,"max": 16}}},
	"Solid": {"type": "Armour","level": 70,"stats": {"Physical Damage Reduction Rating +%": {"min": 17,"max": 19}}},
	"Beetle's": {"type": "Armor and Stun Recovery","level": 1,"stats": {"Local Physical Damage Reduction Rating +%": {"min": 6,"max": 14},"Base Stun Recovery +%": {"min": 6,"max": 7}}},
	"Crab's": {"type": "Armor and Stun Recovery","level": 17,"stats": {"Local Physical Damage Reduction Rating +%": {"min": 15,"max": 23},"Base Stun Recovery +%": {"min": 8,"max": 9}}},
	"Armadillo's": {"type": "Armor and Stun Recovery","level": 29,"stats": {"Local Physical Damage Reduction Rating +%": {"min": 24,"max": 32},"Base Stun Recovery +%": {"min": 10,"max": 11}}},
	"Rhino's": {"type": "Armor and Stun Recovery","level": 42,"stats": {"Local Physical Damage Reduction Rating +%": {"min": 33,"max": 41},"Base Stun Recovery +%": {"min": 12,"max": 13}}},
	"Elephant's": {"type": "Armor and Stun Recovery","level": 60,"stats": {"Local Physical Damage Reduction Rating +%": {"min": 42,"max": 50},"Base Stun Recovery +%": {"min": 14,"max": 15}}},
	"Frosted": {"type": "Damage","level": 2,"stats": {"Base Minimum Added Cold Damage": {"min": 2,"max": 2},"Base Maximum Added Cold Damage": {"min": 4,"max": 4}}},
	"Chilled": {"type": "Damage","level": 13,"stats": {"Base Minimum Added Cold Damage": {"min": 5,"max": 8},"Base Maximum Added Cold Damage": {"min": 11,"max": 13}}},
	"Icy": {"type": "Damage","level": 21,"stats": {"Base Minimum Added Cold Damage": {"min": 8,"max": 11},"Base Maximum Added Cold Damage": {"min": 17,"max": 20}}},
	"Frigid": {"type": "Damage","level": 29,"stats": {"Base Minimum Added Cold Damage": {"min": 11,"max": 15},"Base Maximum Added Cold Damage": {"min": 23,"max": 27}}},
	"Freezing": {"type": "Damage","level": 37,"stats": {"Base Minimum Added Cold Damage": {"min": 14,"max": 19},"Base Maximum Added Cold Damage": {"min": 29,"max": 33}}},
	"Frozen": {"type": "Damage","level": 50,"stats": {"Base Minimum Added Cold Damage": {"min": 19,"max": 25},"Base Maximum Added Cold Damage": {"min": 38,"max": 44}}},
	"Glaciated": {"type": "Damage","level": 60,"stats": {"Base Minimum Added Cold Damage": {"min": 22,"max": 30},"Base Maximum Added Cold Damage": {"min": 45,"max": 53}}},
	"Polar": {"type": "Damage","level": 71,"stats": {"Base Minimum Added Cold Damage": {"min": 26,"max": 35},"Base Maximum Added Cold Damage": {"min": 53,"max": 62}}},
	"Heated": {"type": "Damage","level": 1,"stats": {"Base Minimum Added Fire Damage": {"min": 2,"max": 2},"Base Maximum Added Fire Damage": {"min": 4,"max": 4}}},
	"Smoldering": {"type": "Damage","level": 12,"stats": {"Base Minimum Added Fire Damage": {"min": 6,"max": 8},"Base Maximum Added Fire Damage": {"min": 12,"max": 14}}},
	"Smoking": {"type": "Damage","level": 20,"stats": {"Base Minimum Added Fire Damage": {"min": 9,"max": 12},"Base Maximum Added Fire Damage": {"min": 19,"max": 22}}},
	"Burning": {"type": "Damage","level": 28,"stats": {"Base Minimum Added Fire Damage": {"min": 12,"max": 17},"Base Maximum Added Fire Damage": {"min": 25,"max": 30}}},
	"Flaming": {"type": "Damage","level": 36,"stats": {"Base Minimum Added Fire Damage": {"min": 16,"max": 21},"Base Maximum Added Fire Damage": {"min": 32,"max": 38}}},
	"Scorching": {"type": "Damage","level": 48,"stats": {"Base Minimum Added Fire Damage": {"min": 21,"max": 28},"Base Maximum Added Fire Damage": {"min": 42,"max": 49}}},
	"Incinerating": {"type": "Damage","level": 59,"stats": {"Base Minimum Added Fire Damage": {"min": 25,"max": 34},"Base Maximum Added Fire Damage": {"min": 51,"max": 59}}},
	"Blasting": {"type": "Damage","level": 70,"stats": {"Base Minimum Added Fire Damage": {"min": 29,"max": 40},"Base Maximum Added Fire Damage": {"min": 60,"max": 70}}},
	"Humming": {"type": "Damage","level": 3,"stats": {"Base Minimum Added Lightning Damage": {"min": 1,"max": 1},"Base Maximum Added Lightning Damage": {"min": 9,"max": 10}}},
	"Buzzing": {"type": "Damage","level": 13,"stats": {"Base Minimum Added Lightning Damage": {"min": 1,"max": 2},"Base Maximum Added Lightning Damage": {"min": 24,"max": 25}}},
	"Snapping": {"type": "Damage","level": 22,"stats": {"Base Minimum Added Lightning Damage": {"min": 1,"max": 3},"Base Maximum Added Lightning Damage": {"min": 36,"max": 38}}},
	"Crackling": {"type": "Damage","level": 30,"stats": {"Base Minimum Added Lightning Damage": {"min": 2,"max": 5},"Base Maximum Added Lightning Damage": {"min": 48,"max": 51}}},
	"Sparking": {"type": "Damage","level": 38,"stats": {"Base Minimum Added Lightning Damage": {"min": 3,"max": 6},"Base Maximum Added Lightning Damage": {"min": 59,"max": 63}}},
	"Arcing": {"type": "Damage","level": 50,"stats": {"Base Minimum Added Lightning Damage": {"min": 3,"max": 8},"Base Maximum Added Lightning Damage": {"min": 76,"max": 81}}},
	"Shocking": {"type": "Damage","level": 58,"stats": {"Base Minimum Added Lightning Damage": {"min": 4,"max": 9},"Base Maximum Added Lightning Damage": {"min": 88,"max": 93}}},
	"Discharging": {"type": "Damage","level": 69,"stats": {"Base Minimum Added Lightning Damage": {"min": 5,"max": 11},"Base Maximum Added Lightning Damage": {"min": 103,"max": 109}}},
	"Glinting": {"type": "Damage","level": 5,"stats": {"Base Minimum Added Physical Damage": {"min": 1,"max": 2},"Base Maximum Added Physical Damage": {"min": 2,"max": 3}}},
	"Burnished": {"type": "Damage","level": 14,"stats": {"Base Minimum Added Physical Damage": {"min": 2,"max": 4},"Base Maximum Added Physical Damage": {"min": 6,"max": 7}}},
	"Polished": {"type": "Damage","level": 24,"stats": {"Base Minimum Added Physical Damage": {"min": 4,"max": 6},"Base Maximum Added Physical Damage": {"min": 9,"max": 11}}},
	"Honed": {"type": "Damage","level": 31,"stats": {"Base Minimum Added Physical Damage": {"min": 5,"max": 7},"Base Maximum Added Physical Damage": {"min": 11,"max": 13}}},
	"Gleaming": {"type": "Damage","level": 39,"stats": {"Base Minimum Added Physical Damage": {"min": 7,"max": 9},"Base Maximum Added Physical Damage": {"min": 14,"max": 17}}},
	"Annealed": {"type": "Damage","level": 47,"stats": {"Base Minimum Added Physical Damage": {"min": 8,"max": 11},"Base Maximum Added Physical Damage": {"min": 17,"max": 20}}},
	"Razor Sharp": {"type": "Damage","level": 57,"stats": {"Base Minimum Added Physical Damage": {"min": 10,"max": 13},"Base Maximum Added Physical Damage": {"min": 20,"max": 24}}},
	"Tempered": {"type": "Damage","level": 70,"stats": {"Base Minimum Added Physical Damage": {"min": 12,"max": 16},"Base Maximum Added Physical Damage": {"min": 25,"max": 29}}},
	"Glinting": {"type": "Damage","level": 1,"stats": {"Local Minimum Added Physical Damage": {"min": 1,"max": 1},"Local Maximum Added Physical Damage": {"min": 2,"max": 2}}},
	"Burnished": {"type": "Damage","level": 14,"stats": {"Local Minimum Added Physical Damage": {"min": 4,"max": 5},"Local Maximum Added Physical Damage": {"min": 8,"max": 10}}},
	"Polished": {"type": "Damage","level": 23,"stats": {"Local Minimum Added Physical Damage": {"min": 6,"max": 8},"Local Maximum Added Physical Damage": {"min": 12,"max": 15}}},
	"Honed": {"type": "Damage","level": 30,"stats": {"Local Minimum Added Physical Damage": {"min": 8,"max": 10},"Local Maximum Added Physical Damage": {"min": 16,"max": 19}}},
	"Gleaming": {"type": "Damage","level": 39,"stats": {"Local Minimum Added Physical Damage": {"min": 10,"max": 13},"Local Maximum Added Physical Damage": {"min": 20,"max": 24}}},
	"Annealed": {"type": "Damage","level": 50,"stats": {"Local Minimum Added Physical Damage": {"min": 12,"max": 17},"Local Maximum Added Physical Damage": {"min": 25,"max": 30}}},
	"Razor Sharp": {"type": "Damage","level": 59,"stats": {"Local Minimum Added Physical Damage": {"min": 15,"max": 20},"Local Maximum Added Physical Damage": {"min": 30,"max": 35}}},
	"Tempered": {"type": "Damage","level": 69,"stats": {"Local Minimum Added Physical Damage": {"min": 17,"max": 23},"Local Maximum Added Physical Damage": {"min": 35,"max": 40}}},
	"Heavy": {"type": "Damage Scaling","level": 1,"stats": {"Local Physical Damage +%": {"min": 20,"max": 49}}},
	"Serrated": {"type": "Damage Scaling","level": 11,"stats": {"Local Physical Damage +%": {"min": 50,"max": 69}}},
	"Wicked": {"type": "Damage Scaling","level": 23,"stats": {"Local Physical Damage +%": {"min": 70,"max": 89}}},
	"Vicious": {"type": "Damage Scaling","level": 35,"stats": {"Local Physical Damage +%": {"min": 90,"max": 109}}},
	"Bloodthirsty": {"type": "Damage Scaling","level": 46,"stats": {"Local Physical Damage +%": {"min": 110,"max": 129}}},
	"Cruel": {"type": "Damage Scaling","level": 60,"stats": {"Local Physical Damage +%": {"min": 130,"max": 149}}},
	"Squire's": {"type": "Damage Scaling and Accuracy","level": 1,"stats": {"Local Physical Damage +%": {"min": 10,"max": 24},"Local Accuracy Rating": {"min": 3,"max": 7}}},
	"Journeyman's": {"type": "Damage Scaling and Accuracy","level": 11,"stats": {"Local Physical Damage +%": {"min": 25,"max": 34},"Local Accuracy Rating": {"min": 8,"max": 30}}},
	"Reaver's": {"type": "Damage Scaling and Accuracy","level": 23,"stats": {"Local Physical Damage +%": {"min": 35,"max": 44},"Local Accuracy Rating": {"min": 31,"max": 50}}},
	"Mercenary's": {"type": "Damage Scaling and Accuracy","level": 35,"stats": {"Local Physical Damage +%": {"min": 45,"max": 54},"Local Accuracy Rating": {"min": 51,"max": 64}}},
	"Champion's": {"type": "Damage Scaling and Accuracy","level": 46,"stats": {"Local Physical Damage +%": {"min": 55,"max": 64},"Local Accuracy Rating": {"min": 65,"max": 82}}},
	"Conqueror's": {"type": "Damage Scaling and Accuracy","level": 60,"stats": {"Local Physical Damage +%": {"min": 65,"max": 74},"Local Accuracy Rating": {"min": 83,"max": 99}}},
	"Frosted": {"type": "Elemental Damage","level": 2,"stats": {"Local Minimum Added Cold Damage": {"min": 2,"max": 3},"Local Maximum Added Cold Damage": {"min": 5,"max": 6}}},
	"Chilled": {"type": "Elemental Damage","level": 13,"stats": {"Local Minimum Added Cold Damage": {"min": 8,"max": 11},"Local Maximum Added Cold Damage": {"min": 16,"max": 19}}},
	"Icy": {"type": "Elemental Damage","level": 21,"stats": {"Local Minimum Added Cold Damage": {"min": 12,"max": 16},"Local Maximum Added Cold Damage": {"min": 25,"max": 29}}},
	"Frigid": {"type": "Elemental Damage","level": 29,"stats": {"Local Minimum Added Cold Damage": {"min": 16,"max": 21},"Local Maximum Added Cold Damage": {"min": 32,"max": 38}}},
	"Freezing": {"type": "Elemental Damage","level": 38,"stats": {"Local Minimum Added Cold Damage": {"min": 20,"max": 27},"Local Maximum Added Cold Damage": {"min": 41,"max": 48}}},
	"Frozen": {"type": "Elemental Damage","level": 50,"stats": {"Local Minimum Added Cold Damage": {"min": 26,"max": 35},"Local Maximum Added Cold Damage": {"min": 53,"max": 62}}},
	"Glaciated": {"type": "Elemental Damage","level": 58,"stats": {"Local Minimum Added Cold Damage": {"min": 30,"max": 41},"Local Maximum Added Cold Damage": {"min": 61,"max": 72}}},
	"Polar": {"type": "Elemental Damage","level": 69,"stats": {"Local Minimum Added Cold Damage": {"min": 36,"max": 48},"Local Maximum Added Cold Damage": {"min": 72,"max": 85}}},
	"Heated": {"type": "Elemental Damage","level": 1,"stats": {"Local Minimum Added Fire Damage": {"min": 2,"max": 3},"Local Maximum Added Fire Damage": {"min": 5,"max": 6}}},
	"Smoldering": {"type": "Elemental Damage","level": 12,"stats": {"Local Minimum Added Fire Damage": {"min": 9,"max": 11},"Local Maximum Added Fire Damage": {"min": 18,"max": 20}}},
	"Smoking": {"type": "Elemental Damage","level": 20,"stats": {"Local Minimum Added Fire Damage": {"min": 13,"max": 18},"Local Maximum Added Fire Damage": {"min": 27,"max": 31}}},
	"Burning": {"type": "Elemental Damage","level": 28,"stats": {"Local Minimum Added Fire Damage": {"min": 18,"max": 24},"Local Maximum Added Fire Damage": {"min": 36,"max": 42}}},
	"Flaming": {"type": "Elemental Damage","level": 38,"stats": {"Local Minimum Added Fire Damage": {"min": 23,"max": 31},"Local Maximum Added Fire Damage": {"min": 47,"max": 55}}},
	"Scorching": {"type": "Elemental Damage","level": 50,"stats": {"Local Minimum Added Fire Damage": {"min": 30,"max": 40},"Local Maximum Added Fire Damage": {"min": 61,"max": 71}}},
	"Incinerating": {"type": "Elemental Damage","level": 58,"stats": {"Local Minimum Added Fire Damage": {"min": 35,"max": 47},"Local Maximum Added Fire Damage": {"min": 70,"max": 82}}},
	"Blasting": {"type": "Elemental Damage","level": 68,"stats": {"Local Minimum Added Fire Damage": {"min": 40,"max": 54},"Local Maximum Added Fire Damage": {"min": 81,"max": 95}}},
	"Humming": {"type": "Elemental Damage","level": 3,"stats": {"Local Minimum Added Lightning Damage": {"min": 1,"max": 1},"Local Maximum Added Lightning Damage": {"min": 13,"max": 14}}},
	"Buzzing": {"type": "Elemental Damage","level": 13,"stats": {"Local Minimum Added Lightning Damage": {"min": 1,"max": 3},"Local Maximum Added Lightning Damage": {"min": 33,"max": 35}}},
	"Snapping": {"type": "Elemental Damage","level": 22,"stats": {"Local Minimum Added Lightning Damage": {"min": 2,"max": 5},"Local Maximum Added Lightning Damage": {"min": 51,"max": 54}}},
	"Crackling": {"type": "Elemental Damage","level": 30,"stats": {"Local Minimum Added Lightning Damage": {"min": 3,"max": 7},"Local Maximum Added Lightning Damage": {"min": 67,"max": 71}}},
	"Sparking": {"type": "Elemental Damage","level": 38,"stats": {"Local Minimum Added Lightning Damage": {"min": 4,"max": 8},"Local Maximum Added Lightning Damage": {"min": 83,"max": 88}}},
	"Arcing": {"type": "Elemental Damage","level": 50,"stats": {"Local Minimum Added Lightning Damage": {"min": 5,"max": 11},"Local Maximum Added Lightning Damage": {"min": 107,"max": 113}}},
	"Shocking": {"type": "Elemental Damage","level": 58,"stats": {"Local Minimum Added Lightning Damage": {"min": 6,"max": 13},"Local Maximum Added Lightning Damage": {"min": 123,"max": 130}}},
	"Discharging": {"type": "Elemental Damage","level": 68,"stats": {"Local Minimum Added Lightning Damage": {"min": 7,"max": 15},"Local Maximum Added Lightning Damage": {"min": 143,"max": 151}}},
	"Shining": {"type": "Energy Shield","level": 3,"stats": {"Base Maximum Energy Shield": {"min": 1,"max": 3}}},
	"Glimmering": {"type": "Energy Shield","level": 11,"stats": {"Base Maximum Energy Shield": {"min": 4,"max": 8}}},
	"Glittering": {"type": "Energy Shield","level": 17,"stats": {"Base Maximum Energy Shield": {"min": 9,"max": 12}}},
	"Glowing": {"type": "Energy Shield","level": 23,"stats": {"Base Maximum Energy Shield": {"min": 13,"max": 15}}},
	"Radiating": {"type": "Energy Shield","level": 29,"stats": {"Base Maximum Energy Shield": {"min": 16,"max": 19}}},
	"Pulsing": {"type": "Energy Shield","level": 35,"stats": {"Base Maximum Energy Shield": {"min": 20,"max": 22}}},
	"Seething": {"type": "Energy Shield","level": 42,"stats": {"Base Maximum Energy Shield": {"min": 23,"max": 26}}},
	"Blazing": {"type": "Energy Shield","level": 50,"stats": {"Base Maximum Energy Shield": {"min": 27,"max": 31}}},
	"Scintillating": {"type": "Energy Shield","level": 59,"stats": {"Base Maximum Energy Shield": {"min": 32,"max": 37}}},
	"Incandescent": {"type": "Energy Shield","level": 68,"stats": {"Base Maximum Energy Shield": {"min": 38,"max": 43}}},
	"Shining": {"type": "Energy Shield","level": 3,"stats": {"Local Energy Shield": {"min": 3,"max": 5}}},
	"Glimmering": {"type": "Energy Shield","level": 11,"stats": {"Local Energy Shield": {"min": 6,"max": 8}}},
	"Glittering": {"type": "Energy Shield","level": 17,"stats": {"Local Energy Shield": {"min": 9,"max": 12}}},
	"Glowing": {"type": "Energy Shield","level": 23,"stats": {"Local Energy Shield": {"min": 13,"max": 15}}},
	"Radiating": {"type": "Energy Shield","level": 29,"stats": {"Local Energy Shield": {"min": 16,"max": 19}}},
	"Pulsing": {"type": "Energy Shield","level": 35,"stats": {"Local Energy Shield": {"min": 20,"max": 29}}},
	"Seething": {"type": "Energy Shield","level": 43,"stats": {"Local Energy Shield": {"min": 30,"max": 48}}},
	"Blazing": {"type": "Energy Shield","level": 51,"stats": {"Local Energy Shield": {"min": 49,"max": 72}}},
	"Scintillating": {"type": "Energy Shield","level": 60,"stats": {"Local Energy Shield": {"min": 73,"max": 106}}},
	"Incandescent": {"type": "Energy Shield","level": 69,"stats": {"Local Energy Shield": {"min": 107,"max": 148}}},
	"Protective": {"type": "Energy Shield","level": 3,"stats": {"Local Energy Shield +%": {"min": 11,"max": 28}}},
	"Strong-Willed": {"type": "Energy Shield","level": 18,"stats": {"Local Energy Shield +%": {"min": 29,"max": 46}}},
	"Resolute": {"type": "Energy Shield","level": 30,"stats": {"Local Energy Shield +%": {"min": 47,"max": 64}}},
	"Fearless": {"type": "Energy Shield","level": 44,"stats": {"Local Energy Shield +%": {"min": 65,"max": 120}}},
	"Dauntless": {"type": "Energy Shield","level": 60,"stats": {"Local Energy Shield +%": {"min": 121,"max": 170}}},
	"Protective": {"type": "Energy Shield","level": 3,"stats": {"Maximum Energy Shield +%": {"min": 2,"max": 4}}},
	"Strong-Willed": {"type": "Energy Shield","level": 18,"stats": {"Maximum Energy Shield +%": {"min": 5,"max": 7}}},
	"Resolute": {"type": "Energy Shield","level": 30,"stats": {"Maximum Energy Shield +%": {"min": 8,"max": 10}}},
	"Fearless": {"type": "Energy Shield","level": 42,"stats": {"Maximum Energy Shield +%": {"min": 11,"max": 13}}},
	"Dauntless": {"type": "Energy Shield","level": 56,"stats": {"Maximum Energy Shield +%": {"min": 14,"max": 16}}},
	"Indomitable": {"type": "Energy Shield","level": 70,"stats": {"Maximum Energy Shield +%": {"min": 17,"max": 19}}},
	"Pixie's": {"type": "Energy Shield and Stun Recovery","level": 3,"stats": {"Local Energy Shield +%": {"min": 6,"max": 14},"Base Stun Recovery +%": {"min": 6,"max": 7}}},
	"Gremlin's": {"type": "Energy Shield and Stun Recovery","level": 18,"stats": {"Local Energy Shield +%": {"min": 15,"max": 23},"Base Stun Recovery +%": {"min": 8,"max": 9}}},
	"Boggart's": {"type": "Energy Shield and Stun Recovery","level": 30,"stats": {"Local Energy Shield +%": {"min": 24,"max": 32},"Base Stun Recovery +%": {"min": 10,"max": 11}}},
	"Naga's": {"type": "Energy Shield and Stun Recovery","level": 44,"stats": {"Local Energy Shield +%": {"min": 33,"max": 41},"Base Stun Recovery +%": {"min": 12,"max": 13}}},
	"Djinn's": {"type": "Energy Shield and Stun Recovery","level": 60,"stats": {"Local Energy Shield +%": {"min": 42,"max": 50},"Base Stun Recovery +%": {"min": 14,"max": 15}}},
	"Agile": {"type": "Evasion","level": 1,"stats": {"Base Evasion Rating": {"min": 3,"max": 10}}},
	"Dancer's": {"type": "Evasion","level": 18,"stats": {"Base Evasion Rating": {"min": 11,"max": 35}}},
	"Acrobat's": {"type": "Evasion","level": 29,"stats": {"Base Evasion Rating": {"min": 36,"max": 60}}},
	"Fleet": {"type": "Evasion","level": 42,"stats": {"Base Evasion Rating": {"min": 61,"max": 80}}},
	"Blurred": {"type": "Evasion","level": 58,"stats": {"Base Evasion Rating": {"min": 81,"max": 120}}},
	"Agile": {"type": "Evasion","level": 2,"stats": {"Evasion Rating +%": {"min": 2,"max": 4}}},
	"Dancer's": {"type": "Evasion","level": 19,"stats": {"Evasion Rating +%": {"min": 5,"max": 7}}},
	"Acrobat's": {"type": "Evasion","level": 30,"stats": {"Evasion Rating +%": {"min": 8,"max": 10}}},
	"Fleet": {"type": "Evasion","level": 42,"stats": {"Evasion Rating +%": {"min": 11,"max": 13}}},
	"Blurred": {"type": "Evasion","level": 56,"stats": {"Evasion Rating +%": {"min": 14,"max": 16}}},
	"Phased": {"type": "Evasion","level": 70,"stats": {"Evasion Rating +%": {"min": 17,"max": 19}}},
	"Agile": {"type": "Evasion","level": 1,"stats": {"Local Base Evasion Rating": {"min": 3,"max": 10}}},
	"Dancer's": {"type": "Evasion","level": 18,"stats": {"Local Base Evasion Rating": {"min": 11,"max": 35}}},
	"Acrobat's": {"type": "Evasion","level": 29,"stats": {"Local Base Evasion Rating": {"min": 36,"max": 60}}},
	"Fleet": {"type": "Evasion","level": 42,"stats": {"Local Base Evasion Rating": {"min": 61,"max": 138}}},
	"Blurred": {"type": "Evasion","level": 56,"stats": {"Local Base Evasion Rating": {"min": 139,"max": 322}}},
	"Shade's": {"type": "Evasion","level": 3,"stats": {"Local Evasion Rating +%": {"min": 11,"max": 28}}},
	"Ghost's": {"type": "Evasion","level": 19,"stats": {"Local Evasion Rating +%": {"min": 29,"max": 46}}},
	"Spectre's": {"type": "Evasion","level": 30,"stats": {"Local Evasion Rating +%": {"min": 47,"max": 64}}},
	"Wraith's": {"type": "Evasion","level": 44,"stats": {"Local Evasion Rating +%": {"min": 65,"max": 82}}},
	"Phantasm's": {"type": "Evasion","level": 60,"stats": {"Local Evasion Rating +%": {"min": 83,"max": 100}}},
	"Mosquito's": {"type": "Evasion and Stun Recovery","level": 2,"stats": {"Local Evasion Rating +%": {"min": 6,"max": 14},"Base Stun Recovery +%": {"min": 6,"max": 7}}},
	"Moth's": {"type": "Evasion and Stun Recovery","level": 19,"stats": {"Local Evasion Rating +%": {"min": 15,"max": 23},"Base Stun Recovery +%": {"min": 8,"max": 9}}},
	"Butterfly's": {"type": "Evasion and Stun Recovery","level": 30,"stats": {"Local Evasion Rating +%": {"min": 24,"max": 32},"Base Stun Recovery +%": {"min": 10,"max": 11}}},
	"Wasp's": {"type": "Evasion and Stun Recovery","level": 44,"stats": {"Local Evasion Rating +%": {"min": 33,"max": 41},"Base Stun Recovery +%": {"min": 12,"max": 13}}},
	"Dragonfly's": {"type": "Evasion and Stun Recovery","level": 60,"stats": {"Local Evasion Rating +%": {"min": 42,"max": 50},"Base Stun Recovery +%": {"min": 14,"max": 15}}},
	"Perpetual": {"type": "Flask","level": 3,"stats": {"Local Charges Added +%": {"min": 20,"max": 40}}},
	"Ample": {"type": "Flask","level": 2,"stats": {"Local Extra Max Charges": {"min": 10,"max": 20}}},
	"Saturated": {"type": "Flask","level": 1,"stats": {"Local Flask Amount To Recover +%": {"min": 50,"max": 50},"Local Flask Recovery Speed +%": {"min": -33,"max": -33}}},
	"Cautious": {"type": "Flask","level": 6,"stats": {"Local Flask Amount To Recover When Below Threshold +%": {"min": 100,"max": 100},"Local Flask Life % Threshold For Increased Recovery": {"min": 35,"max": 35}}},
	"Sapping": {"type": "Flask","level": 13,"stats": {"Local Flask Life To Recover +%": {"min": 60,"max": 60},"Local Flask Removes % Of Life Recovery From Mana On Use": {"min": 10,"max": 10}}},
	"Caustic": {"type": "Flask","level": 11,"stats": {"Local Flask Mana To Recover +%": {"min": 60,"max": 60},"Local Flask Removes % Of Mana Recovery From Life On Use": {"min": 15,"max": 15}}},
	"Panicked": {"type": "Flask","level": 9,"stats": {"Local Flask Recover Instantly When Life Below %": {"min": 35,"max": 35},"Local Flask Amount To Recover +%": {"min": -25,"max": -25}}},
	"Seething": {"type": "Flask","level": 7,"stats": {"Local Flask Recovers Instantly": {"min": 1,"max": 1},"Local Flask Amount To Recover +%": {"min": -66,"max": -66}}},
	"Bubbling": {"type": "Flask","level": 3,"stats": {"Local Flask Recovery Amount % To Recover Instantly": {"min": 50,"max": 50},"Local Flask Amount To Recover +%": {"min": -50,"max": -50},"Local Flask Recovery Speed +%": {"min": 135,"max": 135}}},
	"Catalysed": {"type": "Flask","level": 1,"stats": {"Local Flask Recovery Speed +%": {"min": 50,"max": 50}}},
	"Surgeon's": {"type": "Flask","level": 8,"stats": {"Local Recharge On Crit": {"min": 1,"max": 1}}},
	"Avenger's": {"type": "Flask","level": 12,"stats": {"Local Recharge On Take Crit": {"min": 3,"max": 3}}},
	"Thief's ": {"type": "Item Acquisition","level": 16,"stats": {"Base Item Found Quantity +%": {"min": 6,"max": 10}}},
	"Looter's": {"type": "Item Acquisition","level": 43,"stats": {"Base Item Found Quantity +%": {"min": 11,"max": 14}}},
	"Pillager's": {"type": "Item Acquisition","level": 65,"stats": {"Base Item Found Quantity +%": {"min": 15,"max": 19}}},
	"Magpie's": {"type": "Item Acquisition","level": 20,"stats": {"Base Item Found Rarity +%": {"min": 10,"max": 18}}},
	"Pirate's": {"type": "Item Acquisition","level": 39,"stats": {"Base Item Found Rarity +%": {"min": 19,"max": 24}}},
	"Dragon's": {"type": "Item Acquisition","level": 62,"stats": {"Base Item Found Rarity +%": {"min": 25,"max": 30}}},
	"Healthy": {"type": "Life","level": 1,"stats": {"Base Maximum Life": {"min": 10,"max": 19}}},
	"Sanguine": {"type": "Life","level": 11,"stats": {"Base Maximum Life": {"min": 20,"max": 29}}},
	"Stalwart": {"type": "Life","level": 18,"stats": {"Base Maximum Life": {"min": 30,"max": 39}}},
	"Stout": {"type": "Life","level": 24,"stats": {"Base Maximum Life": {"min": 40,"max": 49}}},
	"Robust": {"type": "Life","level": 30,"stats": {"Base Maximum Life": {"min": 50,"max": 59}}},
	"Rotund": {"type": "Life","level": 36,"stats": {"Base Maximum Life": {"min": 60,"max": 69}}},
	"Virile": {"type": "Life","level": 44,"stats": {"Base Maximum Life": {"min": 70,"max": 79}}},
	"Athlete's": {"type": "Life","level": 54,"stats": {"Base Maximum Life": {"min": 80,"max": 89}}},
	"Fecund": {"type": "Life","level": 64,"stats": {"Base Maximum Life": {"min": 90,"max": 99}}},
	"Remora's": {"type": "Life Leech","level": 9,"stats": {"Life Leech From Physical Damage %": {"min": 1,"max": 2}}},
	"Lamprey's": {"type": "Life Leech","level": 25,"stats": {"Life Leech From Physical Damage %": {"min": 3,"max": 5}}},
	"Beryl": {"type": "Mana","level": 1,"stats": {"Base Maximum Mana": {"min": 15,"max": 19}}},
	"Cobalt": {"type": "Mana","level": 11,"stats": {"Base Maximum Mana": {"min": 20,"max": 24}}},
	"Azure": {"type": "Mana","level": 17,"stats": {"Base Maximum Mana": {"min": 25,"max": 29}}},
	"Sapphire": {"type": "Mana","level": 23,"stats": {"Base Maximum Mana": {"min": 30,"max": 34}}},
	"Cerulean": {"type": "Mana","level": 29,"stats": {"Base Maximum Mana": {"min": 35,"max": 39}}},
	"Aqua": {"type": "Mana","level": 35,"stats": {"Base Maximum Mana": {"min": 40,"max": 44}}},
	"Opalescent": {"type": "Mana","level": 42,"stats": {"Base Maximum Mana": {"min": 45,"max": 49}}},
	"Gentian": {"type": "Mana","level": 51,"stats": {"Base Maximum Mana": {"min": 50,"max": 54}}},
	"Chalybeous": {"type": "Mana","level": 60,"stats": {"Base Maximum Mana": {"min": 55,"max": 59}}},
	"Mazarine": {"type": "Mana","level": 69,"stats": {"Base Maximum Mana": {"min": 60,"max": 64}}},
	"Thirsty": {"type": "Mana Leech","level": 9,"stats": {"Mana Leech From Physical Damage %": {"min": 1,"max": 1}}},
	"Runner's": {"type": "Movement Velocity","level": 1,"stats": {"Base Movement Velocity +%": {"min": 10,"max": 10}}},
	"Sprinter's": {"type": "Movement Velocity","level": 15,"stats": {"Base Movement Velocity +%": {"min": 15,"max": 15}}},
	"Stallion's": {"type": "Movement Velocity","level": 30,"stats": {"Base Movement Velocity +%": {"min": 20,"max": 20}}},
	"Gazelle's": {"type": "Movement Velocity","level": 40,"stats": {"Base Movement Velocity +%": {"min": 25,"max": 25}}},
	"Cheetah's": {"type": "Movement Velocity","level": 55,"stats": {"Base Movement Velocity +%": {"min": 30,"max": 30}}},
	"Apprentice's": {"type": "Spell Damage","level": 2,"stats": {"Spell Damage +%": {"min": 10,"max": 19}}},
	"Chanter's": {"type": "Spell Damage","level": 5,"stats": {"Spell Damage +%": {"min": 3,"max": 7}}},
	"Adept's": {"type": "Spell Damage","level": 11,"stats": {"Spell Damage +%": {"min": 20,"max": 29}}},
	"Mage's": {"type": "Spell Damage","level": 20,"stats": {"Spell Damage +%": {"min": 8,"max": 12}}},
	"Scholar's": {"type": "Spell Damage","level": 23,"stats": {"Spell Damage +%": {"min": 30,"max": 39}}},
	"Professor's": {"type": "Spell Damage","level": 35,"stats": {"Spell Damage +%": {"min": 40,"max": 49}}},
	"Sorceror's": {"type": "Spell Damage","level": 38,"stats": {"Spell Damage +%": {"min": 13,"max": 17}}},
	"Occultist's": {"type": "Spell Damage","level": 46,"stats": {"Spell Damage +%": {"min": 50,"max": 59}}},
	"Thaumaturgist's": {"type": "Spell Damage","level": 56,"stats": {"Spell Damage +%": {"min": 18,"max": 22}}},
	"Incanter's": {"type": "Spell Damage","level": 58,"stats": {"Spell Damage +%": {"min": 60,"max": 69}}},
	"Caster's": {"type": "Spell Damage and Mana","level": 2,"stats": {"Spell Damage +%": {"min": 5,"max": 9},"Base Maximum Mana": {"min": 8,"max": 10}}},
	"Magician's": {"type": "Spell Damage and Mana","level": 11,"stats": {"Spell Damage +%": {"min": 10,"max": 14},"Base Maximum Mana": {"min": 11,"max": 13}}},
	"Wizard's": {"type": "Spell Damage and Mana","level": 23,"stats": {"Spell Damage +%": {"min": 15,"max": 19},"Base Maximum Mana": {"min": 14,"max": 16}}},
	"Warlock's": {"type": "Spell Damage and Mana","level": 35,"stats": {"Spell Damage +%": {"min": 20,"max": 24},"Base Maximum Mana": {"min": 17,"max": 19}}},
	"Mage's": {"type": "Spell Damage and Mana","level": 46,"stats": {"Spell Damage +%": {"min": 25,"max": 29},"Base Maximum Mana": {"min": 20,"max": 22}}},
	"Archmage's": {"type": "Spell Damage and Mana","level": 58,"stats": {"Spell Damage +%": {"min": 30,"max": 34},"Base Maximum Mana": {"min": 23,"max": 25}}},
	"Catalyzing": {"type": "Weapon Elemental Damage","level": 4,"stats": {"Weapon Elemental Damage +%": {"min": 5,"max": 10}}},
	"Infusing": {"type": "Weapon Elemental Damage","level": 15,"stats": {"Weapon Elemental Damage +%": {"min": 11,"max": 20}}},
	"Empowering": {"type": "Weapon Elemental Damage","level": 30,"stats": {"Weapon Elemental Damage +%": {"min": 21,"max": 30}}}
};
MOD_SUFFIX_DATA = {
	"of Calm": {"type": "Accuracy","level": 1,"stats": {"Accuracy Rating": {"min": 5,"max": 15}}},
	"of Steadiness": {"type": "Accuracy","level": 12,"stats": {"Accuracy Rating": {"min": 16,"max": 60}}},
	"of Accuracy": {"type": "Accuracy","level": 20,"stats": {"Accuracy Rating": {"min": 61,"max": 100}}},
	"of Precision": {"type": "Accuracy","level": 26,"stats": {"Accuracy Rating": {"min": 101,"max": 130}}},
	"of the Sniper": {"type": "Accuracy","level": 33,"stats": {"Accuracy Rating": {"min": 131,"max": 165}}},
	"of the Marksman": {"type": "Accuracy","level": 41,"stats": {"Accuracy Rating": {"min": 166,"max": 200}}},
	"of the Deadeye": {"type": "Accuracy","level": 50,"stats": {"Accuracy Rating": {"min": 201,"max": 250}}},
	"of the Ranger": {"type": "Accuracy","level": 63,"stats": {"Accuracy Rating": {"min": 251,"max": 320}}},
	"of Calm": {"type": "Accuracy","level": 1,"stats": {"Local Accuracy Rating": {"min": 5,"max": 15}}},
	"of Steadiness": {"type": "Accuracy","level": 12,"stats": {"Local Accuracy Rating": {"min": 16,"max": 60}}},
	"of Accuracy": {"type": "Accuracy","level": 20,"stats": {"Local Accuracy Rating": {"min": 61,"max": 100}}},
	"of Precision": {"type": "Accuracy","level": 26,"stats": {"Local Accuracy Rating": {"min": 101,"max": 130}}},
	"of the Sniper": {"type": "Accuracy","level": 33,"stats": {"Local Accuracy Rating": {"min": 131,"max": 165}}},
	"of the Marksman": {"type": "Accuracy","level": 41,"stats": {"Local Accuracy Rating": {"min": 166,"max": 200}}},
	"of the Deadeye": {"type": "Accuracy","level": 50,"stats": {"Local Accuracy Rating": {"min": 201,"max": 250}}},
	"of the Ranger": {"type": "Accuracy","level": 63,"stats": {"Local Accuracy Rating": {"min": 251,"max": 320}}},
	"of Skill": {"type": "Attack Speed","level": 1,"stats": {"Attack Speed +%": {"min": 5,"max": 7}}},
	"of Ease": {"type": "Attack Speed","level": 11,"stats": {"Attack Speed +%": {"min": 8,"max": 10}}},
	"of Mastery": {"type": "Attack Speed","level": 22,"stats": {"Attack Speed +%": {"min": 11,"max": 13}}},
	"of Skill": {"type": "Attack Speed","level": 1,"stats": {"Local Attack Speed +%": {"min": 6,"max": 9}}},
	"of Ease": {"type": "Attack Speed","level": 11,"stats": {"Local Attack Speed +%": {"min": 5,"max": 10}}},
	"of Mastery": {"type": "Attack Speed","level": 22,"stats": {"Local Attack Speed +%": {"min": 11,"max": 13}}},
	"of Renown": {"type": "Attack Speed","level": 30,"stats": {"Local Attack Speed +%": {"min": 14,"max": 16}}},
	"of Acclaim": {"type": "Attack Speed","level": 37,"stats": {"Local Attack Speed +%": {"min": 17,"max": 19}}},
	"of Fame": {"type": "Attack Speed","level": 45,"stats": {"Local Attack Speed +%": {"min": 20,"max": 22}}},
	"of Infamy": {"type": "Attack Speed","level": 60,"stats": {"Local Attack Speed +%": {"min": 23,"max": 25}}},
	"of the Clouds": {"type": "Attribute Increase","level": 1,"stats": {"Additional All Attributes": {"min": 1,"max": 4}}},
	"of the Sky": {"type": "Attribute Increase","level": 11,"stats": {"Additional All Attributes": {"min": 5,"max": 8}}},
	"of the Meteor": {"type": "Attribute Increase","level": 22,"stats": {"Additional All Attributes": {"min": 9,"max": 12}}},
	"of the Comet": {"type": "Attribute Increase","level": 33,"stats": {"Additional All Attributes": {"min": 13,"max": 16}}},
	"of the Heavens": {"type": "Attribute Increase","level": 44,"stats": {"Additional All Attributes": {"min": 17,"max": 20}}},
	"of the Galaxy": {"type": "Attribute Increase","level": 55,"stats": {"Additional All Attributes": {"min": 21,"max": 24}}},
	"of the Universe": {"type": "Attribute Increase","level": 66,"stats": {"Additional All Attributes": {"min": 25,"max": 28}}},
	"of the Mongoose": {"type": "Attribute Increase","level": 1,"stats": {"Additional Dexterity": {"min": 8,"max": 12}}},
	"of the Lynx": {"type": "Attribute Increase","level": 11,"stats": {"Additional Dexterity": {"min": 13,"max": 17}}},
	"of the Gazelle": {"type": "Attribute Increase","level": 22,"stats": {"Additional Dexterity": {"min": 18,"max": 22}}},
	"of the Panther": {"type": "Attribute Increase","level": 33,"stats": {"Additional Dexterity": {"min": 23,"max": 27}}},
	"of the Leopard": {"type": "Attribute Increase","level": 44,"stats": {"Additional Dexterity": {"min": 28,"max": 32}}},
	"of the Cheetah": {"type": "Attribute Increase","level": 55,"stats": {"Additional Dexterity": {"min": 33,"max": 37}}},
	"of the Faun": {"type": "Attribute Increase","level": 66,"stats": {"Additional Dexterity": {"min": 38,"max": 42}}},
	"of the Pupil": {"type": "Attribute Increase","level": 1,"stats": {"Additional Intelligence": {"min": 8,"max": 12}}},
	"of the Student": {"type": "Attribute Increase","level": 11,"stats": {"Additional Intelligence": {"min": 13,"max": 17}}},
	"of the Prodigy": {"type": "Attribute Increase","level": 22,"stats": {"Additional Intelligence": {"min": 18,"max": 22}}},
	"of the Augur": {"type": "Attribute Increase","level": 33,"stats": {"Additional Intelligence": {"min": 23,"max": 27}}},
	"of the Philosopher": {"type": "Attribute Increase","level": 44,"stats": {"Additional Intelligence": {"min": 28,"max": 32}}},
	"of the Sage": {"type": "Attribute Increase","level": 55,"stats": {"Additional Intelligence": {"min": 33,"max": 37}}},
	"of the Savant": {"type": "Attribute Increase","level": 66,"stats": {"Additional Intelligence": {"min": 38,"max": 42}}},
	"of the Brute": {"type": "Attribute Increase","level": 1,"stats": {"Additional Strength": {"min": 8,"max": 12}}},
	"of the Wrestler": {"type": "Attribute Increase","level": 11,"stats": {"Additional Strength": {"min": 13,"max": 17}}},
	"of the Bear": {"type": "Attribute Increase","level": 22,"stats": {"Additional Strength": {"min": 18,"max": 22}}},
	"of the Lion": {"type": "Attribute Increase","level": 33,"stats": {"Additional Strength": {"min": 23,"max": 27}}},
	"of the Gorilla": {"type": "Attribute Increase","level": 44,"stats": {"Additional Strength": {"min": 28,"max": 32}}},
	"of the Goliath": {"type": "Attribute Increase","level": 55,"stats": {"Additional Strength": {"min": 33,"max": 37}}},
	"of the Leviathan": {"type": "Attribute Increase","level": 66,"stats": {"Additional Strength": {"min": 38,"max": 42}}},
	"of Talent": {"type": "Cast Speed","level": 2,"stats": {"Base Cast Speed +%": {"min": 5,"max": 7}}},
	"of Nimbleness": {"type": "Cast Speed","level": 15,"stats": {"Base Cast Speed +%": {"min": 8,"max": 10}}},
	"of Expertise": {"type": "Cast Speed","level": 30,"stats": {"Base Cast Speed +%": {"min": 11,"max": 13}}},
	"of Legerdemain": {"type": "Cast Speed","level": 40,"stats": {"Base Cast Speed +%": {"min": 14,"max": 16}}},
	"of Prestidigitation": {"type": "Cast Speed","level": 55,"stats": {"Base Cast Speed +%": {"min": 17,"max": 19}}},
	"of Ire": {"type": "Critical Strike","level": 8,"stats": {"Base Critical Strike Multiplier +%": {"min": 7,"max": 12}}},
	"of Anger": {"type": "Critical Strike","level": 21,"stats": {"Base Critical Strike Multiplier +%": {"min": 13,"max": 26}}},
	"of Rage": {"type": "Critical Strike","level": 31,"stats": {"Base Critical Strike Multiplier +%": {"min": 27,"max": 39}}},
	"of Fury": {"type": "Critical Strike","level": 45,"stats": {"Base Critical Strike Multiplier +%": {"min": 40,"max": 53}}},
	"of Ferocity": {"type": "Critical Strike","level": 59,"stats": {"Base Critical Strike Multiplier +%": {"min": 54,"max": 66}}},
	"of Needling": {"type": "Critical Strike","level": 5,"stats": {"Critical Strike Chance +%": {"min": 10,"max": 14}}},
	"of Stinging": {"type": "Critical Strike","level": 20,"stats": {"Critical Strike Chance +%": {"min": 15,"max": 19}}},
	"of Piercing": {"type": "Critical Strike","level": 30,"stats": {"Critical Strike Chance +%": {"min": 20,"max": 24}}},
	"of Puncturing": {"type": "Critical Strike","level": 44,"stats": {"Critical Strike Chance +%": {"min": 25,"max": 29}}},
	"of Penetrating": {"type": "Critical Strike","level": 58,"stats": {"Critical Strike Chance +%": {"min": 30,"max": 34}}},
	"of Needling": {"type": "Critical Strike","level": 1,"stats": {"Local Critical Strike Chance +%": {"min": 10,"max": 14}}},
	"of Stinging": {"type": "Critical Strike","level": 20,"stats": {"Local Critical Strike Chance +%": {"min": 15,"max": 19}}},
	"of Piercing": {"type": "Critical Strike","level": 30,"stats": {"Local Critical Strike Chance +%": {"min": 20,"max": 24}}},
	"of Puncturing": {"type": "Critical Strike","level": 44,"stats": {"Local Critical Strike Chance +%": {"min": 25,"max": 29}}},
	"of Penetrating": {"type": "Critical Strike","level": 59,"stats": {"Local Critical Strike Chance +%": {"min": 30,"max": 34}}},
	"of Ire": {"type": "Critical Strike","level": 8,"stats": {"Local Critical Strike Multiplier +%": {"min": 10,"max": 14}}},
	"of Anger": {"type": "Critical Strike","level": 21,"stats": {"Local Critical Strike Multiplier +%": {"min": 15,"max": 19}}},
	"of Rage": {"type": "Critical Strike","level": 30,"stats": {"Local Critical Strike Multiplier +%": {"min": 20,"max": 24}}},
	"of Fury": {"type": "Critical Strike","level": 44,"stats": {"Local Critical Strike Multiplier +%": {"min": 25,"max": 29}}},
	"of Ferocity": {"type": "Critical Strike","level": 59,"stats": {"Local Critical Strike Multiplier +%": {"min": 30,"max": 34}}},
	"of Menace": {"type": "Critical Strike","level": 11,"stats": {"Spell Critical Strike Chance +%": {"min": 11,"max": 20}}},
	"of Havoc": {"type": "Critical Strike","level": 21,"stats": {"Spell Critical Strike Chance +%": {"min": 20,"max": 39}}},
	"of Disaster": {"type": "Critical Strike","level": 28,"stats": {"Spell Critical Strike Chance +%": {"min": 40,"max": 59}}},
	"of Calamity": {"type": "Critical Strike","level": 41,"stats": {"Spell Critical Strike Chance +%": {"min": 60,"max": 79}}},
	"of Ruin": {"type": "Critical Strike","level": 59,"stats": {"Spell Critical Strike Chance +%": {"min": 80,"max": 99}}},
	"of Snow": {"type": "Elemental Damage Scaling","level": 12,"stats": {"Cold Damage +%": {"min": 3,"max": 7}}},
	"of Sleet": {"type": "Elemental Damage Scaling","level": 24,"stats": {"Cold Damage +%": {"min": 8,"max": 12}}},
	"of Ice": {"type": "Elemental Damage Scaling","level": 36,"stats": {"Cold Damage +%": {"min": 13,"max": 17}}},
	"of Rime": {"type": "Elemental Damage Scaling","level": 50,"stats": {"Cold Damage +%": {"min": 18,"max": 22}}},
	"of Floe": {"type": "Elemental Damage Scaling","level": 64,"stats": {"Cold Damage +%": {"min": 23,"max": 26}}},
	"of Embers": {"type": "Elemental Damage Scaling","level": 8,"stats": {"Fire Damage +%": {"min": 3,"max": 7}}},
	"of Coals": {"type": "Elemental Damage Scaling","level": 22,"stats": {"Fire Damage +%": {"min": 8,"max": 12}}},
	"of Cinders": {"type": "Elemental Damage Scaling","level": 36,"stats": {"Fire Damage +%": {"min": 13,"max": 17}}},
	"of Flames": {"type": "Elemental Damage Scaling","level": 50,"stats": {"Fire Damage +%": {"min": 18,"max": 22}}},
	"of Immolation": {"type": "Elemental Damage Scaling","level": 64,"stats": {"Fire Damage +%": {"min": 23,"max": 26}}},
	"of Sparks": {"type": "Elemental Damage Scaling","level": 10,"stats": {"Lightning Damage +%": {"min": 3,"max": 7}}},
	"of Static": {"type": "Elemental Damage Scaling","level": 23,"stats": {"Lightning Damage +%": {"min": 8,"max": 12}}},
	"of Electricity": {"type": "Elemental Damage Scaling","level": 36,"stats": {"Lightning Damage +%": {"min": 13,"max": 17}}},
	"of Voltage": {"type": "Elemental Damage Scaling","level": 50,"stats": {"Lightning Damage +%": {"min": 18,"max": 22}}},
	"of Discharge": {"type": "Elemental Damage Scaling","level": 64,"stats": {"Lightning Damage +%": {"min": 23,"max": 26}}},
	"of Resolve": {"type": "Energy Shield Recharge Delay","level": 5,"stats": {"Energy Shield Delay -%": {"min": 3,"max": 5}}},
	"of Fortitude": {"type": "Energy Shield Recharge Delay","level": 23,"stats": {"Energy Shield Delay -%": {"min": 6,"max": 8}}},
	"of Will": {"type": "Energy Shield Recharge Delay","level": 35,"stats": {"Energy Shield Delay -%": {"min": 9,"max": 11}}},
	"of Calm": {"type": "Energy Shield Regeneration","level": 7,"stats": {"Energy Shield Regeneration Rate +%": {"min": 10,"max": 19}}},
	"of Concentration": {"type": "Energy Shield Regeneration","level": 21,"stats": {"Energy Shield Regeneration Rate +%": {"min": 20,"max": 29}}},
	"of Focus": {"type": "Energy Shield Regeneration","level": 31,"stats": {"Energy Shield Regeneration Rate +%": {"min": 30,"max": 34}}},
	"of Study": {"type": "Energy Shield Regeneration","level": 45,"stats": {"Energy Shield Regeneration Rate +%": {"min": 40,"max": 49}}},
	"of Clear Mind": {"type": "Energy Shield Regeneration","level": 58,"stats": {"Energy Shield Regeneration Rate +%": {"min": 50,"max": 59}}},
	"of Fending": {"type": "Flask","level": 9,"stats": {"Local Flask Adds Knockback While Healing": {"min": 1,"max": 1}}},
	"of Iron Skin": {"type": "Flask","level": 6,"stats": {"Local Flask Armour +% While Healing": {"min": 60,"max": 100}}},
	"of Dousing": {"type": "Flask","level": 6,"stats": {"Local Flask Dispells Burning": {"min": 1,"max": 1}}},
	"of Heat": {"type": "Flask","level": 4,"stats": {"Local Flask Dispells Freeze And Chill": {"min": 1,"max": 1}}},
	"of Reflexes": {"type": "Flask","level": 8,"stats": {"Local Flask Evasion +% While Healing": {"min": 60,"max": 100}}},
	"of Gluttony": {"type": "Flask","level": 10,"stats": {"Local Flask Life Leech % While Healing": {"min": 2,"max": 2}}},
	"of Craving": {"type": "Flask","level": 12,"stats": {"Local Flask Mana Leech % While Healing": {"min": 2,"max": 2}}},
	"of Animation": {"type": "Flask","level": 10,"stats": {"Local Flask Minion Heal %": {"min": 40,"max": 60}}},
	"of Adrenaline": {"type": "Flask","level": 1,"stats": {"Local Flask Movement Speed +% While Healing": {"min": 20,"max": 30}}},
	"of Resistance": {"type": "Flask","level": 1,"stats": {"Local Flask Resistances +% While Healing": {"min": 20,"max": 30}}},
	"of Steadiness": {"type": "Flask","level": 1,"stats": {"Local Flask Stun Recovery +% While Healing": {"min": 40,"max": 60}}},
	"of Collecting": {"type": "Item Acquisition","level": 2,"stats": {"Base Item Found Quantity +%": {"min": 4,"max": 8}}},
	"of Gathering": {"type": "Item Acquisition","level": 32,"stats": {"Base Item Found Quantity +%": {"min": 9,"max": 12}}},
	"of Hoarding": {"type": "Item Acquisition","level": 55,"stats": {"Base Item Found Quantity +%": {"min": 13,"max": 16}}},
	"of Plunder": {"type": "Item Acquisition","level": 3,"stats": {"Base Item Found Rarity +%": {"min": 6,"max": 14}}},
	"of Raiding": {"type": "Item Acquisition","level": 30,"stats": {"Base Item Found Rarity +%": {"min": 15,"max": 20}}},
	"of Archaeology": {"type": "Item Acquisition","level": 53,"stats": {"Base Item Found Rarity +%": {"min": 21,"max": 26}}},
	"of Rejuvenation": {"type": "Life Gain Per Target","level": 8,"stats": {"Life Gain Per Target": {"min": 2,"max": 2}}},
	"of Restoration": {"type": "Life Gain Per Target","level": 20,"stats": {"Life Gain Per Target": {"min": 3,"max": 3}}},
	"of Regrowth": {"type": "Life Gain Per Target","level": 30,"stats": {"Life Gain Per Target": {"min": 4,"max": 4}}},
	"of Nourishment": {"type": "Life Gain Per Target","level": 40,"stats": {"Life Gain Per Target": {"min": 5,"max": 5}}},
	"of the Newt": {"type": "Life Regeneration","level": 1,"stats": {"Base Life Regeneration Rate Per Minute": {"min": 42,"max": 67}}},
	"of the Lizard": {"type": "Life Regeneration","level": 18,"stats": {"Base Life Regeneration Rate Per Minute": {"min": 96,"max": 142}}},
	"of the Starfish": {"type": "Life Regeneration","level": 30,"stats": {"Base Life Regeneration Rate Per Minute": {"min": 132,"max": 196}}},
	"of the Hydra": {"type": "Life Regeneration","level": 44,"stats": {"Base Life Regeneration Rate Per Minute": {"min": 171,"max": 260}}},
	"of the Troll": {"type": "Life Regeneration","level": 59,"stats": {"Base Life Regeneration Rate Per Minute": {"min": 217,"max": 328}}},
	"of Excitement": {"type": "Mana Regeneration","level": 2,"stats": {"Mana Regeneration Rate +%": {"min": 10,"max": 19}}},
	"of Joy": {"type": "Mana Regeneration","level": 18,"stats": {"Mana Regeneration Rate +%": {"min": 20,"max": 29}}},
	"of Elation": {"type": "Mana Regeneration","level": 29,"stats": {"Mana Regeneration Rate +%": {"min": 30,"max": 39}}},
	"of Bliss": {"type": "Mana Regeneration","level": 42,"stats": {"Mana Regeneration Rate +%": {"min": 40,"max": 49}}},
	"of Euphoria": {"type": "Mana Regeneration","level": 55,"stats": {"Mana Regeneration Rate +%": {"min": 50,"max": 59}}},
	"of the Inuit": {"type": "Resistance","level": 1,"stats": {"Base Cold Damage Resistance %": {"min": 6,"max": 11}}},
	"of the Seal": {"type": "Resistance","level": 14,"stats": {"Base Cold Damage Resistance %": {"min": 12,"max": 17}}},
	"of the Penguin": {"type": "Resistance","level": 26,"stats": {"Base Cold Damage Resistance %": {"min": 18,"max": 23}}},
	"of the Yeti": {"type": "Resistance","level": 38,"stats": {"Base Cold Damage Resistance %": {"min": 24,"max": 29}}},
	"of the Walrus": {"type": "Resistance","level": 50,"stats": {"Base Cold Damage Resistance %": {"min": 30,"max": 35}}},
	"of the Polar Bear": {"type": "Resistance","level": 60,"stats": {"Base Cold Damage Resistance %": {"min": 36,"max": 41}}},
	"of the Whelpling": {"type": "Resistance","level": 1,"stats": {"Base Fire Damage Resistance %": {"min": 6,"max": 11}}},
	"of the Salamander": {"type": "Resistance","level": 12,"stats": {"Base Fire Damage Resistance %": {"min": 12,"max": 17}}},
	"of the Drake": {"type": "Resistance","level": 24,"stats": {"Base Fire Damage Resistance %": {"min": 18,"max": 23}}},
	"of the Kiln": {"type": "Resistance","level": 36,"stats": {"Base Fire Damage Resistance %": {"min": 24,"max": 29}}},
	"of the Furnace": {"type": "Resistance","level": 48,"stats": {"Base Fire Damage Resistance %": {"min": 30,"max": 35}}},
	"of the Volcano": {"type": "Resistance","level": 60,"stats": {"Base Fire Damage Resistance %": {"min": 36,"max": 41}}},
	"of the Cloud": {"type": "Resistance","level": 1,"stats": {"Base Lightning Damage Resistance %": {"min": 6,"max": 11}}},
	"of the Squall": {"type": "Resistance","level": 13,"stats": {"Base Lightning Damage Resistance %": {"min": 12,"max": 17}}},
	"of the Storm": {"type": "Resistance","level": 25,"stats": {"Base Lightning Damage Resistance %": {"min": 18,"max": 23}}},
	"of the Thunderhead": {"type": "Resistance","level": 37,"stats": {"Base Lightning Damage Resistance %": {"min": 24,"max": 29}}},
	"of the Tempest": {"type": "Resistance","level": 49,"stats": {"Base Lightning Damage Resistance %": {"min": 30,"max": 35}}},
	"of the Maelstrom": {"type": "Resistance","level": 60,"stats": {"Base Lightning Damage Resistance %": {"min": 36,"max": 41}}},
	"of the Crystal": {"type": "Resistance","level": 12,"stats": {"Base Resist All Elements %": {"min": 3,"max": 5}}},
	"of the Prism": {"type": "Resistance","level": 24,"stats": {"Base Resist All Elements %": {"min": 6,"max": 8}}},
	"of the Kaleidoscope": {"type": "Resistance","level": 36,"stats": {"Base Resist All Elements %": {"min": 9,"max": 11}}},
	"of Variegation": {"type": "Resistance","level": 48,"stats": {"Base Resist All Elements %": {"min": 12,"max": 14}}},
	"of the Rainbow": {"type": "Resistance","level": 60,"stats": {"Base Resist All Elements %": {"min": 15,"max": 16}}},
	"of Impact": {"type": "Stun","level": 5,"stats": {"Base Stun Duration +%": {"min": 11,"max": 15}}},
	"of Dazing": {"type": "Stun","level": 18,"stats": {"Base Stun Duration +%": {"min": 16,"max": 20}}},
	"of Stunning": {"type": "Stun","level": 30,"stats": {"Base Stun Duration +%": {"min": 21,"max": 25}}},
	"of Slamming": {"type": "Stun","level": 44,"stats": {"Base Stun Duration +%": {"min": 26,"max": 30}}},
	"of Staggering": {"type": "Stun","level": 58,"stats": {"Base Stun Duration +%": {"min": 31,"max": 35}}},
	"of Thick Skin": {"type": "Stun","level": 1,"stats": {"Base Stun Recovery +%": {"min": 11,"max": 13}}},
	"of Stone Skin": {"type": "Stun","level": 17,"stats": {"Base Stun Recovery +%": {"min": 14,"max": 16}}},
	"of Iron Skin": {"type": "Stun","level": 28,"stats": {"Base Stun Recovery +%": {"min": 17,"max": 19}}},
	"of Steel Skin": {"type": "Stun","level": 42,"stats": {"Base Stun Recovery +%": {"min": 20,"max": 22}}},
	"of Adamantite Skin": {"type": "Stun","level": 56,"stats": {"Base Stun Recovery +%": {"min": 23,"max": 25}}},
	"of the Pugilist": {"type": "Stun","level": 5,"stats": {"Base Stun Threshold Reduction +%": {"min": 5,"max": 7}}},
	"of the Brawler": {"type": "Stun","level": 20,"stats": {"Base Stun Threshold Reduction +%": {"min": 8,"max": 9}}},
	"of the Boxer": {"type": "Stun","level": 30,"stats": {"Base Stun Threshold Reduction +%": {"min": 10,"max": 11}}},
	"of the Combatant": {"type": "Stun","level": 44,"stats": {"Base Stun Threshold Reduction +%": {"min": 12,"max": 13}}},
	"of the Gladiator": {"type": "Stun","level": 58,"stats": {"Base Stun Threshold Reduction +%": {"min": 14,"max": 15}}}
};
